[workspace]
members = ["rum-agent"]

[package]
name = "rum"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
facet = "0.43"
facet-toml = "0.43"
miette = { version = "7", features = ["fancy"] }
thiserror = "2"
indicatif = "0.17"
console = "0.15"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "stream"] }
dirs = "6"
virt = "0.4"
futures-util = "0.3"
facet-value = "0.43"
facet-yaml = "0.43"
facet-xml = "0.43"
facet-json = "0.43"
inquire = "0.7"
ssh-key = { version = "0.6", features = ["ed25519", "rand_core", "getrandom"] }
rand_core = { version = "0.6", features = ["getrandom"] }
notify = "8"
russh = "0.57.0"
rum-agent = { path = "rum-agent", artifact = "bin", lib = true, target = "x86_64-unknown-linux-musl" }
tokio-vsock = "0.7"
roam = "0.6"
roam-stream = "0.6"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
